// Authority Alerts Page
// System-wide alert overview

'use client';

import React, { useEffect, useState } from 'react';
import { DashboardLayout } from '@/components/layout/DashboardLayout';
import { PageHeader } from '@/components/layout/PageHeader';
import { AlertCard } from '@/components/dashboard/AlertCard';
import { LoadingSpinner } from '@/components/ui/LoadingState';
import { AUTHORITY_NAV_ITEMS, DEMO_USERS } from '@/constants';
import { getAllAlerts } from '@/services/api';
import { Alert } from '@/types';

export default function AuthorityAlertsPage() {
  const [loading, setLoading] = useState(true);
  const [alerts, setAlerts] = useState<Alert[]>([]);
  
  useEffect(() => {
    async function loadData() {
      try {
        const data = await getAllAlerts();
        setAlerts(data);
      } catch (error) {
        console.error('Error loading alerts:', error);
      } finally {
        setLoading(false);
      }
    }
    
    loadData();
  }, []);
  
  if (loading) {
    return (
      <DashboardLayout userName={DEMO_USERS.AUTHORITY.name} userRole="Authority" navItems={AUTHORITY_NAV_ITEMS}>
        <LoadingSpinner size="lg" />
      </DashboardLayout>
    );
  }
  
  return (
    <DashboardLayout userName={DEMO_USERS.AUTHORITY.name} userRole="Authority" navItems={AUTHORITY_NAV_ITEMS}>
      <PageHeader
        title="System Alerts"
        description="All alerts generated by the monitoring system"
      />
      
      <div className="space-y-6">
        {alerts.map((alert) => (
          <AlertCard key={alert.id} alert={alert} showFullDetails={true} />
        ))}
      </div>
    </DashboardLayout>
  );
}
